server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:

      routes:
        - id: employeeModule
          url: http://localhost:8081/
          predicates:
            - Path=/employee/**
        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**